spring:
  freemarker:
    suffix: '.html'
    templateEncoding: 'UTF-8'
  datasource:
    name: postgresSQLDataSource
    url: jdbc:postgresql://127.0.0.1:5432/mydb?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: mmq
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.postgresql.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
server:
  servlet-path: '/springboot-test2'
  port: 9090
mybatis:
  type-aliases-package: com.test.entity
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

